#!/bin/bash
#Ryan Houck
#Last updated on April 16, 2018
#Queries to restart the computer

#EXIT CODES:
 #0: No errors
 #1: User authentification failed.

echo "Do you want to restart? Please respond with [y/N]."
read input
while [ "$input" != "y" ] && [ "$input" != "n" ] && [ "$input" != "Y" ] && [ "$input" != "N" ]; do
  echo "Please give valid input."
  read input
done
if [ "$input" == "y" ] || [ "$input" == "Y" ]; then
  sudo shutdown -r now
  if [ $? == 0 ]; then
    echo "Restarting."
    exit 0
  else
    echo "Failed user authentification, restart aborted."
    exit 1
  fi
else
  echo "Restart aborted."
  exit 0
fi
